### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AlexPresso** [OneLiberty/moonlight-chrome-tizen#10]
That's not an issue, I just wanted to thank you for maintaining this project.

The old version was making me experience a lot of stutter (as well as the issue making it impossible to add host). Now everything works smoothly.

Please keep the amazing work :)

**Comment by OneLiberty** [comment]
@AlexPresso 
Thank you for your kind words ! It's always rewarding to know that i've helped in some way. Especially considering my next to zero knowledge in any coding language or in the usage of GitHub or anything related. 
I learned a lot doing this ! 

> Please keep the amazing work :)

I will ! 
Again, Thank you :)
