### ISSUE TITLE
Feature Request : Bigger focus on selected applicaiton/game 

### ISSUE THREAD

**Issue by dbz400** [OneLiberty/moonlight-chrome-tizen#11]
During navigation , sometimes may feel difficult to see which one is the focus one/select one. Much appreciated if the focus one can show bit bigger than the non-selected one.

**Comment by OneLiberty** [comment]
Isn't it already done ? 
Can't verify right now, but I believe the selected game/app is bigger than the others. 

Or are you asking to make it bigger ?

**Comment by AlexPresso** [comment]
Yes, it's already done on my side, but I also noticed that when we only have one game in the list, we can't make a difference between game focused or not. Adding a border would be nice imo :)

**Comment by dbz400** [comment]
Yes , bigger or even with a border would be nice .

**Comment by OneLiberty** [comment]
> Yes, it's already done on my side, but I also noticed that when we only have one game in the list, we can't make a difference between game focused or not. Adding a border would be nice imo :)

Never tested that before today (Sunshine has 2 apps by default), and indeed you can't really see (unless doing a little "up -> down" with gamepad or remote. 

@raven02 i tried to make it bigger (going from 1.1 to 1.15) but it messes with the top bar (the one with the back button and the quit current game) and i don't know how to add a border ...

I didn't have much time, and i still don't for the few coming weeks, but i'll keep trying.

**Comment by dbz400** [comment]
@AlexPresso  Thanks for the PR. do you have the binary that I can test with ?

**Comment by OneLiberty** [comment]
@raven02 Took a while, but should be done.
