### ISSUE TITLE
Mouse emulation ? 

### ISSUE THREAD

**Issue by JeromeDesseaux** [OneLiberty/moonlight-chrome-tizen#15]
Hi! 

Thanks for the work you provide on this topic. It’s highly appreciated! 

I’d like to know if mouse emulation (triggered holding « start » on Xbox controller) is working using this fork? 

thanks again for everything you’ve done on this topic! 

Update : To anyone wondering this, I installed the app and haven't yet found a way to make mouse emulation working.

**Comment by OneLiberty** [comment]
That would be a welcomed feature ! 
I'll try to work on that, i just don't know if i'll be able to do it.

**Comment by OneLiberty** [comment]
Should be done as of 1.2.1.
