### ISSUE TITLE
Infinite loading loop

### ISSUE THREAD

**Issue by codedbyk0Lm** [OneLiberty/moonlight-chrome-tizen#18]
Stumbled across your Reddit post stating that the submit IP button would be fixed with your fork.
But, the app does not open, it shows an infinite loop at "Loading Moonlight Plugin..." resulting in auto exiting after a couple of minutes without any error message.

UE50TU8072UXXH

I have tried reinstalling it, and opening in while developer mode is enabled and disabled, resulting in the same infinite loop.

P.s. the KyroFrCode version does open on this TV, yet as stated the submit IP button is buggy where it sometimes auto submits and sometimes just does nothing. Selecting the button itself is not possible.

**Comment by henryfa2** [comment]
Did you install the latest version, published 20 hours ago(commit https://github.com/KyroFrCode/moonlight-chrome-tizen/commit/636bd7bdce8dc10cc91e1e3d23d24d9360b4af51)? 
It should have fixed this issue.

**Comment by codedbyk0Lm** [comment]
> Did you install the latest version, published 20 hours ago(commit [KyroFrCode@636bd7b](https://github.com/KyroFrCode/moonlight-chrome-tizen/commit/636bd7bdce8dc10cc91e1e3d23d24d9360b4af51))? It should have fixed this issue.

You are 100% right, i build the container yesterday morning, a little bit before this update released but didnt have the time to create a ticket and did not check for an update just now!
Updated the image, thanks for your help!
