### ISSUE TITLE
Failed to install application

### ISSUE THREAD

**Issue by ajagnanan** [OneLiberty/moonlight-chrome-tizen#26]
I keep getting a failure right at the beginning of the install. It's a new install, but I checked and the app is not installed yet on the TV. 

Install logs
```
Installing the package...
--------------------
Platform log view
--------------------
install MoonLightS.MoonlightWasm
package_path /home/owner/share/tmp/sdk_tools/tmp/Moonlight.wgt
was_install_app return WAS_TRUE
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] install failed[118019]
spend time for wascmd is [634]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:02.070
```

**Comment by jacoblu** [comment]
@ajagnanan I am seeing a similar issue, just curious if you were able to solve your issue? And if so, how?

**Comment by ajagnanan** [comment]
@jacoblu I wasn’t, my tv is a 2018 model with Tizen 4.0. The minimum required is Tizen 5.5.
