### ISSUE TITLE
AV1 Support

### ISSUE THREAD

**Issue by sven-pke** [OneLiberty/moonlight-chrome-tizen#31]
Hello,

Sunshine supports AV1 streaming with Nvidia Ampere cards. Is it possible to get that feature to receive that stream 
with moonlight tizen? 

Best regards

**Comment by henryfa2** [comment]
Hello there,
Yes I am working on it.

**Comment by henryfa2** [comment]
AV1 Main8 / AV1 Main10 available on my repo : https://github.com/henryfa2/moonlight-chrome-tizen
I'll make a PR later on that repo

**Comment by sven-pke** [comment]
Awesome! Thank you!
