### ISSUE TITLE
Delete unnecessary host PCs?

### ISSUE THREAD

**Issue by Tumatutuma** [OneLiberty/moonlight-chrome-tizen#38]
I tried to reinstall and/or update Sunshine and Moonlight but because of that I'm stuck with two excessive icons indicating the same host.
![photo_2024-04-11_16-28-35](https://github.com/OneLiberty/moonlight-chrome-tizen/assets/160958841/0f99b69c-4e5b-4046-b8b4-780e84155824)
Is there a way to delete host PCs which are no longer necessary from the main panel of the Moonlight app?

**Comment by OneLiberty** [comment]
Sure, you can either use a mouse to click the - button on the top right corner of the host. 
Or you can press the select button on the gamepad while hovering over a host to prompt the delete host dialogue.

**Comment by Tumatutuma** [comment]
Thanks, that fixed my issue! I didn't know I can use a gamepad or a mouse BEFORE entering Steam Big Picture.
