### ISSUE TITLE
Feature Request: Wake on Lan

### ISSUE THREAD

**Issue by ricknijhuis** [OneLiberty/moonlight-chrome-tizen#39]
I was unable to find a way to use wake over Lan, I know my setup supports it as I am able to get it working on android for example. I think it would be a nice addition if possible.

**Comment by OneLiberty** [comment]
I don't know if that's doable as is. 
To do so, we need to get the mac address of the host we want to wake up. 

I'll check a bit. 
Any ideas are welcomed.

**Comment by brapacz** [comment]
It would be awesome.
@OneLiberty - what exactly is the problem here? Getting a MAC addr?

**Comment by OneLiberty** [comment]
@brapacz 
Nah, getting the mac isn't an issue at all, it's more sending the packet. Tizen have pretty limited networking capabilities, but i should be able to cook something with the socket extension

**Comment by zenaror** [comment]
@OneLiberty For some reason, the WoL is not working anymore :(

I was able to wake using other devices..
