### ISSUE TITLE
Main screen exceding 18 elements (games) is not scrolling to show elements from 19 onward

### ISSUE THREAD

**Issue by monaco-errante** [OneLiberty/moonlight-chrome-tizen#41]
After successfully launched Moonlight, in the main server screen, my list include more than 18 elements thus starting from element 19 onward they are partially shown. When scrolling to the #19 the screen does not scroll and it is not possible to see what is selected.

SYSTEM
SAMSUNG TV (QBQ90 50 inches)
Moonlight Tizen v1.2.1 installed (USB method)
PC with RTX 3070ti and SUNSHINE (v0.23.1)

HOW TO REPLICATE
Create more than 18 applications in Sunshine, launch Moonlight app on TV and enter main menu

![screen_not_scrolling](https://github.com/OneLiberty/moonlight-chrome-tizen/assets/168285651/cbb74243-f4e4-44e1-a0da-74d21296c3e8)

**Comment by OneLiberty** [comment]
Wow, never thought of that. 
I've only used the two base app (desktop and steam) tbh. 

Def need to check that. 
Thanks for the bug report. 

I'll keep you informed.

**Comment by monaco-errante** [comment]
Pretty unusual indeed 😃  I am used to get shorcuts for most played games instead of going through Playnite or Steam Big Picture lists
😄

**Comment by OneLiberty** [comment]
Just to add to this, it seems like it's already working using a mouse to scroll. 
It's really gamepad related (or remote). 

Did not find a way to fix it yet tho

**Comment by monaco-errante** [comment]
> Just to add to this, it seems like it's already working using a mouse to scroll. It's really gamepad related (or remote).

Yes, I confirm I get the same behaviour with gamepad and remote. One note (I am not sure it can help) but on both only LEFT-RIGHT keys are working, while TOP and BOTTOM do not navigate in the list but allow to go on top left/top right options (close app and back to moonlight main menu). I will give a try with a BT mouse to check if I am getting the same behaviour you reported

> Did not find a way to fix it yet tho

Don't worry, I am using Playnite (gamestream_launchpad) workaround to get the full list of games fully navigable with the gamepad

**Comment by OneLiberty** [comment]
> but on both only LEFT-RIGHT keys are working

This is intended behavior as the app is designed that way. 
I'm trying to make use of up/down as well but that's for later. 

> Don't worry, I am using Playnite (gamestream_launchpad) workaround to get the full list of games fully navigable with the gamepad

Sure, for now i'd suggest to anyone that experience the issue to use playnite/steam BP to launch your games. 
But i'll will eventually find a way to fix this !

**Comment by monaco-errante** [comment]
> But i'll will eventually find a way to fix this !

Tnx!low priority on this, better having other fixes first (like 5.1 sound or enhanced selected item or any other 😝)

**Comment by gschintgen** [comment]
Yeah, I can confirm this issue. Also that up/down isn't working. At first I thought my second controller wasn't working either :-)
But no hurry.
