### ISSUE TITLE
Error : Initial Ping timeout 

### ISSUE THREAD

**Issue by freemanmusiz** [OneLiberty/moonlight-chrome-tizen#47]
I have setup the Sunshine on my PC, and installed Moonlight on both my Sony and Samsung TVs. For the Sony, it was straight forward, and for the Samsung, I followed the guide to enable Developer mode and deployed Moonlight manually.

Moonlight worked on both TVs with the primary display, however, I wanted to be able to turn off the primary display, so I got a HDMI dummy adapter and changed the Output to "\\.\DISPLAY2". This worked fine with the Sony TV, however, on the Samsung TV, I keep getting the Connection Terminated error in Moonlight, and in the Sunshine log, I see "Error: Initial Ping Timeout ". 

There is not enough information for me to further troubleshoot the issue, but I believe the Sunshine configuration is correct, as it is working with Moonlight on the Sony TV.  Any help is greatly appreciated.

**Comment by OneLiberty** [comment]
don't jumpscare me with a title like that ^^

Try changing the codec to HEVC (make sure to reboot the app after changing the codec by long pressing the return button).
If it doesn't work change the bitrate to something lower than 30. 

Else, if none option worked you can get the debug logs #9 to help diagnose

**Comment by freemanmusiz** [comment]
Sorry, I am new to this app, I will try out your suggestions and report back. Thanks.

**Comment by freemanmusiz** [comment]
It's working now, thanks a million. Now I have to configure the games to launch on the second monitor.

**Comment by OneLiberty** [comment]
Perfect ! Glad it worked :) 
If everything is ok for you, you can close the issue (I can do it too if you want :D)
