### ISSUE TITLE
v1.2.1 for usb expired 

### ISSUE THREAD

**Issue by Davidoo379** [OneLiberty/moonlight-chrome-tizen#50]
Samsung tv shows message that applications has expired

**Comment by OneLiberty** [comment]
done please retry, keep in mind that the docker install is a better way of installing it.
And i don't need to update it every unknown time period

**Comment by Davidoo379** [comment]
> done please retry, keep in mind that the docker install is a better way of installing it. And i don't need to update it every unknown time period

I know that but I'm not that technical so the USB way is very user-friendly. Thank you for the fix
