### ISSUE TITLE
Release 1.2.1 USB Install Validity Expired

### ISSUE THREAD

**Issue by alexmaurizio** [OneLiberty/moonlight-chrome-tizen#51]
As the title states, today I tried opening up my previously working 1.2.1 install in my Samsung QN800B TV installed through the userwidget method, and the TV refuses to start the app with:

ERROR
Cannot start the app because the validity period expired 

(translated from IT)

This is something probably related to the embedded widget. I tried reinstalling to no avail.

This is just to let you know, I will attempt the regular install process now. Thanks!

**Comment by OneLiberty** [comment]
I've re-uploded the file, should work now. 
Thanks for pointing it out :)

**Comment by brodin** [comment]
Hi @OneLiberty !

Now the same thing happened to me - what part of the install is expiring, is it something that I can help make more robust? :)

**Comment by JungleJango** [comment]
Hi, I've tried to install on my S90D and it gives this same message.
