### ISSUE TITLE
Controller works with the TV, but not with Moonlight

### ISSUE THREAD

**Issue by DiegoOdissey** [OneLiberty/moonlight-chrome-tizen#53]
I have successfully installed moonlight on my Samsung TV running on Tizen 6.0, the streaming works fine and I paired my Nintendo Switch Pro Controller to the TV, everything works fine, I can control the UI, but the controller won't work with Moonlight. I also tried a DualShock 4 controller but it didn't work either. I'm using Bluetooth connection since the USB ports are hard to reach.

Anybody knows a fix?
Thank you!

**Comment by OneLiberty** [comment]
Switch pro doesn't work, probably driver issues or smt. What's your tv model ? 
Dualshock 4 shouldn't be an issue at all tho...

**Comment by DiegoOdissey** [comment]
Sorry, I forgot to mention that my DualShock controller is not original. My TV model is QE55Q67AAUXXH.

I’ll try as soon as I can with an original controller.
Great work btw!

**Comment by DiegoOdissey** [comment]
I just tried and with the official DualShock 4 and it worked perfectly! Surprisingly it even worked with the unofficial one!

thank you so much for this application!
