### ISSUE TITLE
Cannot start stream with tv remote controller

### ISSUE THREAD

**Issue by Sephyz** [OneLiberty/moonlight-chrome-tizen#57]
Updated to latest today and I am now unable to start a stream using my TV's remote (TV model is GQ55QN95BATXZG). If I highlight the host and press the Confirm button on my remote, nothing happens.
The remote controller works normally when adding a host (Can select add host, type the IP and confirm).

If I connect a PS5 Dualsense controller, I can successfully select the host by pressing the OPTIONS button only. After doing that, I can use my remote controller to select a game to stream and confirm as expected.

**Comment by Icedrow** [comment]
You have to press the green coloured key on remote or the multicolored one on the right on "smart remote", yes it is annoying and should be rolled back to direct press

**Comment by Sephyz** [comment]
@Icedrow Thanks that worked. It's very unintuitive and there are so many steps to go through for a single action: gotta press this multicolored button to open settings, scroll down to numbers, scroll down again to coloured buttons and then select the green one.
![image](https://github.com/user-attachments/assets/9852b0c8-5066-4f40-a01c-67255be97c71)

**Comment by michael-vedeler** [comment]
Green button doesn't seem to work for me.. when is this going to be fixed to work as intended?

**Comment by OneLiberty** [comment]
I might have messed up somewhere, i'll check
