### ISSUE TITLE
Parsing Error when installing

### ISSUE THREAD

**Issue by im-weiyang** [OneLiberty/moonlight-chrome-tizen#60]
Sorry if this issue is too naive:

I followed the instructions (including the Prerequisites. When I was doing the last step of installing, it showed failed:

![Screenshot 2024-08-20 101943](https://github.com/user-attachments/assets/1caf45e8-a1c3-4ff4-ae0b-b9988cd35f1d)

**moonlight@7b0e09f4aa69:~$ tizen install -n Moonlight.wgt -t UN65RU740DFXZA
Transferring the package...
Transferred the package: /home/moonlight/Moonlight.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install MoonLightS.MoonlightWasm
package_path /home/owner/share/tmp/sdk_tools/tmp/Moonlight.wgt
was_install_app return WAS_TRUE
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] install failed[118, -19], reason: Parsing error :
spend time for wascmd is [944]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:01.759
moonlight@7b0e09f4aa69:~$**

Can anyone could help with this? Thank you so much!

# Read before posting an issue
If you have an issue, please consider the following before:

- Have you tried __updating__:
  - Your operating system
  - Geforce Experience (mention if in beta)
  - Chrome to the latest version
  - The Moonlight client
- Have you tried __pinging__ your host from the client?
- If streaming __over the internet__:
  - Have you followed the [guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide)?
  - Have you opened all ports to they correct protocols (udp or tcp)
- Have you enabled __hardware acceleration__?
  - Check under `chrome://settings/system` to enable it
  - Check under `chrome://flags/#disable-accelerated-video-decode` for video hardware acceleration
  - Check under `chrome://gpu` for:
    - Video Decode: "Hardware accelerated"
    - WebGL: "Hardware accelerated"
    - WebGL2: "Hardware accelerated"
- Have you __enabled NaCL__?
  - Check under `chrome://flags/#enable-nacl` to enable it
  - Are you running Linux? if so, install Chrome from official ppa

If you still have problems, post them in the issues section with info, logs and screenshots if possible

**Comment by MrPhaze62** [comment]
Whats your tv model?

That error usually happens is if this port does not support your tizen version/samsung tv. This port supports up from tizenOS 5.5 and above. Tvs older than that does not support this version of moonlight port.

However there's a version of moonlight that should work with yours and any older tvs linked here.

https://github.com/OneLiberty/moonlight-tizen-nacl 

I will warn you it does have issues so check out the issues in that github page.

**Comment by im-weiyang** [comment]
Thank you so much! I tried this one and it installed successfully! And thank you for the warning. I wasn't able to proceed to the controller step though, because the moonlight showed "Error 521 Streamer couldnt be initialized". After searching it might be due to the TV cannot run Geforce Experience with higher version. Do you have any suggestions on this? Thanks!

**Comment by MrPhaze62** [comment]
are you using nvidia gamestream? if so that is discontinued. sunshine is more updated and open source alternative to nvidia. would recommend to disable/delete nvidia gamestream if you have it and grab sunshine instead to work with moonlight.

although ive never experienced that error. 

also as you're using that fork in the github I've linked, i would recommend to open an issue there as that is more suited for older samsung tvs.
