### ISSUE TITLE
._Moonlight.tmg, invalid app package for security check failed! []

### ISSUE THREAD

**Issue by eduardomozart** [OneLiberty/moonlight-chrome-tizen#64]
Hello,
I have a UN43T5300AGXZD TV and the following error is being thrown when attempting to install Moonlight over USB:
![IMG_1559](https://github.com/user-attachments/assets/19521c62-ec1b-461d-a783-6fdd8d42b394)

**Comment by OneLiberty** [comment]
Usb is not supported anymore install via docker

**Comment by eduardomozart** [comment]
Please update the Release instructions as such.

**Comment by OneLiberty** [comment]
will do on next release.
