### ISSUE TITLE
USB User App Validity Expired on S90D

### ISSUE THREAD

**Issue by JungleJango** [OneLiberty/moonlight-chrome-tizen#65]
Hi, I've tried to install on my S90D and it gives this "User App Validity Expired" message.

**Comment by OneLiberty** [comment]
Hi, please try the installation via docker, more specifically this : https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37#issuecomment-2118982596 for a 2024 model

**Comment by OneLiberty** [comment]
fixed with scheduled releases
