### ISSUE TITLE
Installation fails on latest Samsung Firmware (2013 OneUI)

### ISSUE THREAD

**Issue by davycptan** [OneLiberty/moonlight-chrome-tizen#68]
- Model TV: s95c
- Firmware version: 2013 (OneUI)

Log output

`PS C:\WINDOWS\system32> docker run -it --rm ghcr.io/oneliberty/moonlight-chrome-tizen:samsung_wasm
moonlight@97f9f42ed3b4:~$ sdb connect 192.168.0.238
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.0.238:26101 ...
connected to 192.168.0.238:26101
moonlight@97f9f42ed3b4:~$ sdb devices
List of devices attached
192.168.0.238:26101     device          QE65S95CATXXU
moonlight@97f9f42ed3b4:~$ tizen install -n Moonlight.wgt -t QE65S95CATXXU
Transferring the package...
Transferred the package: /home/moonlight/Moonlight.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install MoonLightS.MoonlightWasm
package_path /home/owner/share/tmp/sdk_tools/tmp/Moonlight.wgt
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] installing[9]
app_id[MoonLightS.MoonlightWasm] installing[19]
app_id[MoonLightS.MoonlightWasm] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [1115]ms
Failed to install Tizen application.
Total time: 00:00:02.364`

**Comment by MrPhaze62** [comment]
See here: https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37#issuecomment-2118982596

**Comment by OneLiberty** [comment]
do you already have the app installed ?

**Comment by davycptan** [comment]
> do you already have the app installed ?

Hi, Before the Samsung TV Firmware upgrade Moonlight was working fine, after the Firmware upgrade I was getting an error, something like 'server not responding' bad memory on my part :)

Deleted the APP and tried the install which seemed to work but the app wasn't showing on the TV
Tried a second time and started to receive the Certificate error 

I was having trouble following the Tizen Studio - Step 2
Ended up using the USB method which was super quick to install on the TV

**Comment by OneLiberty** [comment]
Well, this is the kind of issues that occurs when the app is already install, to update it, you have to uninstall it before. 
`SDB` can help if you don't know if it's still installed 

`sdb shell 0 vd_applist` 
`sdb -s <tv_Ip> shell 0 applist | grep -i -e 'moonlight'` if you have grep 


`sdb -s <tv_Ip> shell 0 vd_appuninstall <app_id>`
Or 
`tizen uninstall -p <app_id>` <--- for moonlight <app_id> looks like `MoonLightS.MoonlightWasm`  You can get it with the above `sdb` commands. 



Anyway, the issues is fixed you can close it :)

**Comment by davycptan** [comment]
Thanks for the uninstall commands

I guess there must have been some remnants of Moonlight on the TV after I deleted the APP
If it occurs again I'll try the above uninstall commands thanks :)
