### ISSUE TITLE
HDR super bright

### ISSUE THREAD

**Issue by Joshuffle** [OneLiberty/moonlight-chrome-tizen#69]
Hi,

My apologies if this isn't the correct path but,
When I turn on HDR within windows and HDR within the setting in the app on the tv as noted in the project, the overall image just looks VERY blown out and bright, like its trying to put HDR on top of the already there HDR image, when I turn off HDR within windows it looks normal (SDR) again but it does mean I can't use HDR at all when streaming to my tv, am I missing something or is the setting non functional as of yet?

Will add image later after work if it helps.

**Comment by OneLiberty** [comment]
Are you using a Main10 Codec ?

**Comment by Joshuffle** [comment]
Thanks! Unironically the first instantly useful answer I've gotten on a tech based forum.

Will check tonight if that fixes it, it was on h264 but now the wife put it on hevc main 10, or would you personally recommend av1 main 10? (having taken a look online seems hevc will be better suited due to lower performance requirement but idk what extra magic you've added)

Also thank you for your hard work, I tried to donate a tenner on coffee but sadly don't have a creditcard.

**Comment by OneLiberty** [comment]
Well, it depends if your graphic card supports AV1 or not, if you're unsure, keep HEVC. 
Trying AV1 while not supported will just fallback on HEVC

**Comment by Joshuffle** [comment]
I have a RTX 3070 which if i'm not mistaken has a dedicated AV1 decoder, just unsure if lower bandwith is more desired or less strain on the limited power of the TV's internals.

**Comment by OneLiberty** [comment]
No av1 on 30 series

**Comment by Joshuffle** [comment]
https://www.nvidia.com/en-us/geforce/news/gfecnt/202009/rtx-30-series-av1-decoding/

Ah I'm guessing decoding only isn't enough, only encoding from 40 series onwards.

**Comment by Joshuffle** [comment]
Just wanted to say it worked! Thought it didn't as it was still a bit bright but that's just the difference of settings between my tv and monitor, it's no longer burning my retinas and in game it looks superb.

I would also recommend those who think their connection is bad or their bluetooth to their pc on the other side of the room is lagging, lock your game's FPS to something that the GPU isn't being pushed to 100%, turns out that fixed all my other issues. (also saw you were working on internal controller mapping, great! takes out my last doubt for input lag and I highly support it (unless ONE UI, tizen 8, finally comes with the option internally but I also kinda doubt it).

Have a good one, and thank you for your amazing support :)
