### ISSUE TITLE
Unable to install Moonlight on latest Samsung Tizen 9.0 M2 update

### ISSUE THREAD

**Issue by carl-1997** [OneLiberty/moonlight-chrome-tizen#70]
Just updated my Samsung S95C TV to the latest software update and the moonlight app appears to have been removed from the TV.

Went to re-install using the instructions provided and get the following error:
![image](https://github.com/user-attachments/assets/a68041d7-abd3-4027-9d83-f7a934f31a0d)

Absolutely love this app so hoping this can be resolved quickly!

**Comment by OneLiberty** [comment]
You'll have to resolve it more or less by yourself 
You're now on tizen 8.0 so follow https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37

I can't do anything for that 

I can just recommend to not update your tv

**Comment by carl-1997** [comment]
This solution worked! Thank you so much :)
