### ISSUE TITLE
Keyboard and mouse with OneUI update

### ISSUE THREAD

**Issue by jrbarto** [OneLiberty/moonlight-chrome-tizen#71]
My Samsung TV recently had an update to version 2011. This update came with a massive One UI overhaul and update and a bunch of new features. Previously, I was able to use a USB connected mouse and keyboard while streaming games via moonlight. However, now it is no longer working. Either One UI or other os update woth 2011 seems to have made a change to the way the keyboard and mouse function. In some apps (like Geforce Now) the keyboard and mouse are still functional (you can left click buttons and they work). But, now for the Moonlight app left clicking cannot actually select anything and right click brings up a menu that emulates the remote:
![Screenshot 2024-11-09 01:09:41](https://github.com/user-attachments/assets/2ccde49b-14c1-4aa9-a551-49391643e8ae)

They do nothing neither in game nor in the Moonlight menu itself (in the screenshot above I cannot actually click the host or any of the options). The keyboard can tab through the buttons in the menu above, but it doesn't work in games.

I'm not sure if there is a way to fix this or if this is just a change on Tizen or due to the One UI update that makes it no longer functional. I am just looking for some possible guidance or assurance that there is nothing that can be done as this is just how the peripherals function after this update. Thanks.

**Comment by jrbarto** [comment]
The only mention i could find of that interface when you right click that emulates the remote is here where it's taking about how to enable mouse support in an app: https://developer.samsung.com/smarttv/develop/guides/user-interaction/mouse.html

I'm not sure if that emulation menu has always been there on the moonlight main menu and i just didn't notice. It does state: "This is used if the application does not support input from mouse pointing-device-support='disable' but supports floating menu floating.navigation='true'.".But what's definitely changed is the mouse and keyboard not functioning at all when streaming. Also, i didn't notice it before, but it is displaying the "mouse control is unavailable" message that it says pops up when that value is disabled.

It is strange though because it is set to enable here: https://github.com/OneLiberty/moonlight-chrome-tizen/blob/65afc7844f25370dc8db22c8dfa30c5a51460797/res/config.xml#L20 and according to that page it would only show that menu if it were disabled.

**Comment by OneLiberty** [comment]
Well it appears we need to add `<tizen:metadata key="http://samsung.com/tv/metadata/floating.navigation" value="false"/>` this in the config.xml 

It's specific to tizen 8.0

**Comment by OneLiberty** [comment]
should be fixed in the latest release

**Comment by jrbarto** [comment]
Thank you so much for the quick fix!
