### ISSUE TITLE
Certificate issue after ONE UI update

### ISSUE THREAD

**Issue by McMeim** [OneLiberty/moonlight-chrome-tizen#76]
Hey
I already installed moonlight on my S95C 77Inch and it worked great.
After I updated the firmware to the latest ONE UI, i tried to install the app in the same way i did before. 
(In the old firmware I first tried with USB which wasn't successful and than moved to do it with docker).
I'm trying to install latest release with the new firmware and i keep getting the same error - 

connected to *** MY TV IP***
moonlight@675c016eea3a:~$ sdb devices
List of devices attached 
***MY TV IP***    device          QE77S95CATXSQ
moonlight@675c016eea3a:~$ tizen install -n Moonlight.wgt -t QE77S95CATXSQ
Transferring the package...
Transferred the package: /home/moonlight/Moonlight.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install MoonLightS.MoonlightWasm
package_path /home/owner/share/tmp/sdk_tools/tmp/Moonlight.wgt
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] installing[9]
app_id[MoonLightS.MoonlightWasm] installing[19]
app_id[MoonLightS.MoonlightWasm] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [1218]ms
Failed to install Tizen application.
Total time: 00:00:02.413

After it failed over and over, I also tried to build the package with Tizen studio and then install it, but it didnt work(when I tried to install it didn't give back any errors, but the app wasn't installed). 

Any thoughts/solutions?

**Comment by OneLiberty** [comment]
Look here 
https://github.com/OneLiberty/moonlight-chrome-tizen/issues/37
