### ISSUE TITLE
UE65CU8000XTK Samsung One UI update

### ISSUE THREAD

**Issue by Erdem96isik** [OneLiberty/moonlight-chrome-tizen#81]
Hello, I had just started using the app. But last week I got a new update on my TV named One UI and after that the app got deleted by itself. When I tried to install the app again I got an error:

 install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>

I've tried installing tizen studio but I couldn't create the certificate. Is there any way to handle it ?

**Comment by OneLiberty** [comment]
#37 take a look at that

**Comment by Erdem96isik** [comment]
Thanks I got it.
