### ISSUE TITLE
Check certificate error : Invalid certificate chain

### ISSUE THREAD

**Issue by G89R-Moritz** [OneLiberty/moonlight-chrome-tizen#82]
Hi,

I’m encountering an issue while installing the Moonlight.wgt on my Tizen TV using the provided instructions. The installation fails with the following error:

app_id[MoonLightS.MoonlightWasm] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>

I’ve followed the steps exactly as described. Could you advise on how to resolve this certificate issue?

Thank you!

**Comment by OneLiberty** [comment]
likely duplicate of #37 
Feel free to re-open if it's not the case

**Comment by G89R-Moritz** [comment]
It worked. Thank you! :D
